eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8088
spring:
  application:
    name: admin-data-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/admin_data_db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:  
      generate_statistics: true